#############################################################################
# Makefile for building: qtmindmap-qtmindmap.app/Contents/MacOS/qtmindmap-qtmindmap
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  qtmindmap-qtmindmap.pro
# Template: app
# Command: /Users/feng/local/Qt5/5.5/clang_64/bin/qmake -o Makefile qtmindmap-qtmindmap.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../local/Qt5/5.5/clang_64/lib/QtSvg.framework/Headers -I../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers -I../../local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers -I../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../local/Qt5/5.5/clang_64/mkspecs/macx-clang -F/Users/feng/local/Qt5/5.5/clang_64/lib
QMAKE         = /Users/feng/local/Qt5/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtmindmap-qtmindmap1.0.0
DISTDIR = /Users/feng/code/qtmindmap-qtmindmap/.tmp/qtmindmap-qtmindmap1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/Users/feng/local/Qt5/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/feng/local/Qt5/5.5/clang_64/lib -framework QtSvg -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtXml -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/argumentparser.cpp \
		src/edge.cpp \
		src/graphwidget.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/node.cpp \
		src/systemtray.cpp qrc_qtmindmap.cpp \
		moc_argumentparser.cpp \
		moc_graphwidget.cpp \
		moc_mainwindow.cpp \
		moc_systemtray.cpp
OBJECTS       = argumentparser.o \
		edge.o \
		graphwidget.o \
		main.o \
		mainwindow.o \
		node.o \
		systemtray.o \
		qrc_qtmindmap.o \
		moc_argumentparser.o \
		moc_graphwidget.o \
		moc_mainwindow.o \
		moc_systemtray.o
DIST          = ../../local/Qt5/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/qdevice.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/features/device_config.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/unix.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/mac.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/macx.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/clang.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/qconfig.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../local/Qt5/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/default_post.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/qt.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/resources.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/moc.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/uic.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/yacc.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/lex.prf \
		qtmindmap-qtmindmap.pro include/argumentparser.h \
		include/edge.h \
		include/graphwidget.h \
		include/mainwindow.h \
		include/node.h \
		include/systemtray.h src/argumentparser.cpp \
		src/edge.cpp \
		src/graphwidget.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/node.cpp \
		src/systemtray.cpp
QMAKE_TARGET  = qtmindmap-qtmindmap
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qtmindmap-qtmindmap.app/Contents/MacOS/qtmindmap-qtmindmap

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@test -d qtmindmap-qtmindmap.app/Contents/MacOS/ || mkdir -p qtmindmap-qtmindmap.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qtmindmap-qtmindmap.pro ../../local/Qt5/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../local/Qt5/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/qdevice.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/features/device_config.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/unix.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/mac.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/macx.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/clang.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/qconfig.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../local/Qt5/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../local/Qt5/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/default_post.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/qt.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/resources.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/moc.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/uic.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/yacc.prf \
		../../local/Qt5/5.5/clang_64/mkspecs/features/lex.prf \
		qtmindmap-qtmindmap.pro \
		images/qtmindmap.qrc \
		/Users/feng/local/Qt5/5.5/clang_64/lib/QtSvg.framework/QtSvg.prl \
		/Users/feng/local/Qt5/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/feng/local/Qt5/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/feng/local/Qt5/5.5/clang_64/lib/QtXml.framework/QtXml.prl \
		/Users/feng/local/Qt5/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile qtmindmap-qtmindmap.pro
../../local/Qt5/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../local/Qt5/5.5/clang_64/mkspecs/qdevice.pri:
../../local/Qt5/5.5/clang_64/mkspecs/features/device_config.prf:
../../local/Qt5/5.5/clang_64/mkspecs/common/unix.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/mac.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/macx.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/sanitize.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/clang.conf:
../../local/Qt5/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../local/Qt5/5.5/clang_64/mkspecs/qconfig.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../local/Qt5/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../local/Qt5/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/qt_config.prf:
../../local/Qt5/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../local/Qt5/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../local/Qt5/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/default_pre.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/default_post.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/warn_on.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/qt.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/resources.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/moc.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/uic.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/exceptions.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/yacc.prf:
../../local/Qt5/5.5/clang_64/mkspecs/features/lex.prf:
qtmindmap-qtmindmap.pro:
images/qtmindmap.qrc:
/Users/feng/local/Qt5/5.5/clang_64/lib/QtSvg.framework/QtSvg.prl:
/Users/feng/local/Qt5/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/feng/local/Qt5/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/feng/local/Qt5/5.5/clang_64/lib/QtXml.framework/QtXml.prl:
/Users/feng/local/Qt5/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qtmindmap-qtmindmap.pro

qmake_all: FORCE

qtmindmap-qtmindmap.app/Contents/PkgInfo: 
	@test -d qtmindmap-qtmindmap.app/Contents || mkdir -p qtmindmap-qtmindmap.app/Contents
	@$(DEL_FILE) qtmindmap-qtmindmap.app/Contents/PkgInfo
	@echo "APPL????" > qtmindmap-qtmindmap.app/Contents/PkgInfo
qtmindmap-qtmindmap.app/Contents/Resources/empty.lproj: 
	@test -d qtmindmap-qtmindmap.app/Contents/Resources || mkdir -p qtmindmap-qtmindmap.app/Contents/Resources
	@touch qtmindmap-qtmindmap.app/Contents/Resources/empty.lproj
	
qtmindmap-qtmindmap.app/Contents/Info.plist: 
	@test -d qtmindmap-qtmindmap.app/Contents || mkdir -p qtmindmap-qtmindmap.app/Contents
	@$(DEL_FILE) qtmindmap-qtmindmap.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,anything.qtmindmap-qtmindmap,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,qtmindmap-qtmindmap,g" -e "s,@TYPEINFO@,????,g" ../../local/Qt5/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >qtmindmap-qtmindmap.app/Contents/Info.plist

all: Makefile \
		qtmindmap-qtmindmap.app/Contents/PkgInfo \
		qtmindmap-qtmindmap.app/Contents/Resources/empty.lproj \
		qtmindmap-qtmindmap.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents images/qtmindmap.qrc $(DISTDIR)/
	$(COPY_FILE) --parents include/argumentparser.h include/edge.h include/graphwidget.h include/mainwindow.h include/node.h include/systemtray.h $(DISTDIR)/
	$(COPY_FILE) --parents src/argumentparser.cpp src/edge.cpp src/graphwidget.cpp src/main.cpp src/mainwindow.cpp src/node.cpp src/systemtray.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui $(DISTDIR)/
	$(COPY_FILE) --parents lang/qtmindmap_hu.ts lang/qtmindmap_nb_NO.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r qtmindmap-qtmindmap.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_qtmindmap.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qtmindmap.cpp
qrc_qtmindmap.cpp: images/qtmindmap.qrc \
		images/help-browser.svg \
		images/mail-attachment.svg \
		images/dialog-information.svg \
		images/user-trash-full.svg \
		images/applications-system.svg \
		images/dialog-warning.svg \
		images/system-users.svg \
		images/x-office-calendar.svg \
		images/qtmindmap.svg
	/Users/feng/local/Qt5/5.5/clang_64/bin/rcc -name qtmindmap images/qtmindmap.qrc -o qrc_qtmindmap.cpp

compiler_moc_header_make_all: moc_argumentparser.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_systemtray.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_argumentparser.cpp moc_graphwidget.cpp moc_mainwindow.cpp moc_systemtray.cpp
moc_argumentparser.cpp: ../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		include/argumentparser.h
	/Users/feng/local/Qt5/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/feng/local/Qt5/5.5/clang_64/mkspecs/macx-clang -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtSvg.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/feng/local/Qt5/5.5/clang_64/lib include/argumentparser.h -o moc_argumentparser.cpp

moc_graphwidget.cpp: ../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		include/graphwidget.h \
		include/graphwidget.h
	/Users/feng/local/Qt5/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/feng/local/Qt5/5.5/clang_64/mkspecs/macx-clang -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtSvg.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/feng/local/Qt5/5.5/clang_64/lib include/graphwidget.h -o moc_graphwidget.cpp

moc_mainwindow.cpp: ../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QSignalMapper \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		include/mainwindow.h
	/Users/feng/local/Qt5/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/feng/local/Qt5/5.5/clang_64/mkspecs/macx-clang -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtSvg.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/feng/local/Qt5/5.5/clang_64/lib include/mainwindow.h -o moc_mainwindow.cpp

moc_systemtray.cpp: ../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		include/mainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QSignalMapper \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		include/systemtray.h
	/Users/feng/local/Qt5/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/feng/local/Qt5/5.5/clang_64/mkspecs/macx-clang -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/code/qtmindmap-qtmindmap -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtSvg.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/feng/local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/feng/local/Qt5/5.5/clang_64/lib include/systemtray.h -o moc_systemtray.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui
	/Users/feng/local/Qt5/5.5/clang_64/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

argumentparser.o: src/argumentparser.cpp include/argumentparser.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QFileInfo \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o argumentparser.o src/argumentparser.cpp

edge.o: src/edge.cpp ../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o src/edge.cpp

graphwidget.o: src/graphwidget.cpp include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QStatusBar \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qstatusbar.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers/QtXml \
		../../local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers/qtxmlglobal.h \
		../../local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers/qdom.h \
		../../local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers/qxml.h \
		../../local/Qt5/5.5/clang_64/lib/QtXml.framework/Headers/qtxmlversion.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QColorDialog \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qcolordialog.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		include/mainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QSignalMapper \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o src/graphwidget.cpp

main.o: src/main.cpp ../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QtGui \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qaccessible.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qaccessiblebridge.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qaccessibleplugin.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qbitmap.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qiconengine.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qiconengineplugin.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qimage.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qimageiohandler.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qimagereader.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qimagewriter.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qmovie.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpicture.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpictureformatplugin.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpixmapcache.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qstandarditemmodel.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qclipboard.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qdrag.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qgenericplugin.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qgenericpluginfactory.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qinputmethod.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qkeysequence.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qoffscreensurface.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglcontext.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevicewindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpalette.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpixelformat.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qrasterwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qscreen.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qsessionmanager.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qstylehints.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qsurface.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qsurfaceformat.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtouchdevice.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qwindowdefs.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qgenericmatrix.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix4x4.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qquaternion.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qvector3d.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qvector4d.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopengl.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglbuffer.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopengldebug.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglframebufferobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglfunctions.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpaintdevice.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglpixeltransferoptions.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglshaderprogram.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopengltexture.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopengltimerquery.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglversionfunctions.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qopenglvertexarrayobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qbackingstore.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qmatrix.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpagedpaintdevice.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpagelayout.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpagesize.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpaintdevice.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpaintengine.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpainterpath.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpdfwriter.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpolygon.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qregion.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qrgb.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtransform.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qabstracttextdocumentlayout.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qfont.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qfontdatabase.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qfontinfo.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qfontmetrics.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qglyphrun.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qrawfont.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qstatictext.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qsyntaxhighlighter.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentfragment.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocumentwriter.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextformat.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextlayout.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextlist.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextoption.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtexttable.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qdesktopservices.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtguiversion.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QRegExp \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QTranslator \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		include/mainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QSignalMapper \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		include/systemtray.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		include/argumentparser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QSignalMapper \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		ui_mainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QFileDialog \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qfiledialog.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

node.o: src/node.cpp include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QStyleOption \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qstyleoption.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextDocument \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextdocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o src/node.cpp

systemtray.o: src/systemtray.cpp include/systemtray.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QObject \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QAction \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qaction.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMenu \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmenu.h \
		include/mainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/QSignalMapper \
		../../local/Qt5/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		include/graphwidget.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsScene \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsscene.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qevent.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsSceneMouseEvent \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicssceneevent.h \
		include/node.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsTextItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/QTextCursor \
		../../local/Qt5/5.5/clang_64/lib/QtGui.framework/Headers/qtextcursor.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsDropShadowEffect \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		include/edge.h \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItem \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../local/Qt5/5.5/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o systemtray.o src/systemtray.cpp

qrc_qtmindmap.o: qrc_qtmindmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qtmindmap.o qrc_qtmindmap.cpp

moc_argumentparser.o: moc_argumentparser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_argumentparser.o moc_argumentparser.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_systemtray.o: moc_systemtray.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_systemtray.o moc_systemtray.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

